### ISSUE TITLE
Fehler in der Attributliste bei disable

### ISSUE THREAD

**Issue by christoph-morrison** [fhem/uba#7]
![image](https://user-images.githubusercontent.com/30689373/79150655-713dde80-7dc9-11ea-8af9-b84a33e67458.png)
Quelle: https://github.com/fhem/uba/blob/613c3e68140c7733d60fc0862f8224c05894d910/FHEM/60_uba.pm#L176

**Comment by florian-asche** [comment]
Ist im Development Branch gefixed. Danke für den Bugreport.
